# Generated by Django 3.0.4 on 2020-03-04 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(max_length=100)),
                ('input_meta_data', models.CharField(blank=True, max_length=5000, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('NEWSPAPER', 'Newspaper'), ('SOCIALMEDIA', 'socialmedia')], max_length=20, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
